reserved_tokens = {
    "Placeholder": r"^__Placeholder__$",
    "Float Literal": r"^-?[0-9]+\.[0-9]+",
    "Integer Literal": r"^-?[0-9]+",
    "String Literal": r'"([^"]*)"',
    "Boolean Literal": r"^((WIN)|(FAIL))",
    "Type Literal": r"^(NOOB|NUMBR|NUMBAR|YARN|TROOF)",
    "Program Start Delimiter": r"^HAI",
    "Program End Delimiter": r"^KTHXBYE",
    "Single-line Comment Delimiter": r"^BTW",
    "Multi-line Comment Delimiter": r"^OBTW",
    "Multi-line Comment End": r"^TLDR",
    "Variable Declaration": r"^I HAS A",
    "Variable Initialization": r"^ITZ",
    "Variable Assignment": r"^R",
    "Any": r"^ANY OF",
    "All": r"^ALL OF",
    "Anyall Delimiter": r"^MKAY",
    "Operation Delimiter": r"^AN",
    "Print": r"^VISIBLE",
    "Input": r"^GIMMEH",
    "Concatenate": r"^SMOOSH",
    "Add": r"^SUM OF",
    "Subtract": r"^DIFF OF",
    "Multiply": r"^PRODUKT OF",
    "Divide": r"^QUOSHUNT OF",
    "Modulo": r"^MOD OF",
    "Max": r"^BIGGR OF",
    "Min": r"^SMALLR OF",
    "And": r"^BOTH OF",
    "Or": r"^EITHER OF",
    "Xor": r"^WON OF",
    "Not": r"^NOT",
    "Loop Start Delimiter": r"^IM IN YR",
    "Loop Increment": r"^UPPIN",
    "Loop Decrement": r"^NERFIN",
    "Loop-Variable Delimiter": r"^YR",
    "Loop Until": r"^TIL",
    "Loop While": r"^WILE",
    "Loop End Delimiter": r"^IM OUTTA YR",
    "Equal": r"^BOTH SAEM",
    "Not Equal": r"^DIFFRINT",
    "Concatenate": r"^SMOOSH",
    "If-Then Start Delimiter": r"^O RLY\?",
    "If": r"^YA RLY",
    "Else": r"^NO WAI",
    "Switch Start Delimiter": r"^WTF\?",
    "Default": "^OMGWTF",
    "Case": "^OMG",
    "Break": "^GTFO",
    "Condition End Delimiter": r"^OIC",
    "Typecasting Declaration": r"^MAEK",
    "Typecasting Reassignment": r"^IS NOW A",
    "Typecasting Assignment": r"^A",
    "Implicit Symbol": r"^IT",
    "Identifier": r"^([a-zA-Z][a-zA-Z_0-9]*)"
}